const fs = require('fs');
const path = require('path');
const srcDir = path.resolve(__dirname, '..', 'src');

// 1. Sparkline.tsx
fs.writeFileSync(path.join(srcDir, 'components/charts/Sparkline.tsx'), [
  'import React, { useEffect, useRef } from "react";',
  '',
  'interface SparklineProps {',
  '  data: number[];',
  '  isPositive?: boolean;',
  '  width?: number;',
  '  height?: number;',
  '  className?: string;',
  '}',
  '',
  'export const Sparkline: React.FC<SparklineProps> = ({',
  '  data,',
  '  isPositive = true,',
  '  width = 110,',
  '  height = 36,',
  '  className = ""',
  '}) => {',
  '  const canvasRef = useRef<HTMLCanvasElement | null>(null);',
  '',
  '  useEffect(() => {',
  '    const canvas = canvasRef.current;',
  '    if (!canvas || !data || data.length < 2) return;',
  '    const ctx = canvas.getContext("2d");',
  '    if (!ctx) return;',
  '',
  '    const dpr = window.devicePixelRatio || 1;',
  '    canvas.width = width * dpr;',
  '    canvas.height = height * dpr;',
  '    ctx.scale(dpr, dpr);',
  '',
  '    ctx.clearRect(0, 0, width, height);',
  '',
  '    const min = Math.min(...data);',
  '    const max = Math.max(...data);',
  '    const range = max - min || 1;',
  '    const padding = 4;',
  '    const drawHeight = height - padding * 2;',
  '    const stepX = (width - padding * 2) / (data.length - 1);',
  '',
  '    const strokeColor = isPositive ? "#35C98A" : "#F05D5E";',
  '    const fillColor = isPositive ? "rgba(53, 201, 138, 0.12)" : "rgba(240, 93, 94, 0.12)";',
  '',
  '    ctx.beginPath();',
  '    data.forEach((val, i) => {',
  '      const x = padding + i * stepX;',
  '      const y = height - padding - ((val - min) / range) * drawHeight;',
  '      if (i === 0) ctx.moveTo(x, y);',
  '      else ctx.lineTo(x, y);',
  '    });',
  '',
  '    // Stroke line',
  '    ctx.strokeStyle = strokeColor;',
  '    ctx.lineWidth = 1.8;',
  '    ctx.lineJoin = "round";',
  '    ctx.lineCap = "round";',
  '    ctx.stroke();',
  '',
  '    // Fill gradient below line',
  '    ctx.lineTo(width - padding, height);',
  '    ctx.lineTo(padding, height);',
  '    ctx.closePath();',
  '    ctx.fillStyle = fillColor;',
  '    ctx.fill();',
  '  }, [data, isPositive, width, height]);',
  '',
  '  return (',
  '    <canvas',
  '      ref={canvasRef}',
  '      style={{ width, height }}',
  '      className={`inline-block flex-shrink-0 ${className}`}',
  '    />',
  '  );',
  '};'
].join('\n'));

// 2. StockChart.tsx
fs.writeFileSync(path.join(srcDir, 'components/charts/StockChart.tsx'), [
  'import React, { useEffect, useRef, useState, useCallback } from "react";',
  'import { HistoricalPrice, TimeFrame } from "../../types";',
  'import { BarChart3, TrendingUp, Maximize2 } from "lucide-react";',
  '',
  'interface StockChartProps {',
  '  data: HistoricalPrice[];',
  '  symbol: string;',
  '  timeframe: TimeFrame;',
  '  onTimeframeChange: (tf: TimeFrame) => void;',
  '  height?: number;',
  '  className?: string;',
  '}',
  '',
  'export const StockChart: React.FC<StockChartProps> = ({',
  '  data,',
  '  symbol,',
  '  timeframe,',
  '  onTimeframeChange,',
  '  height = 360,',
  '  className = ""',
  '}) => {',
  '  const canvasRef = useRef<HTMLCanvasElement | null>(null);',
  '  const containerRef = useRef<HTMLDivElement | null>(null);',
  '  const [chartType, setChartType] = useState<"candle" | "line">("candle");',
  '  const [hoveredIndex, setHoveredIndex] = useState<number | null>(null);',
  '',
  '  const timeframes: TimeFrame[] = ["1D", "1W", "1M", "3M", "1Y"];',
  '',
  '  const drawChart = useCallback(() => {',
  '    const canvas = canvasRef.current;',
  '    if (!canvas || !data || data.length === 0) return;',
  '    const ctx = canvas.getContext("2d");',
  '    if (!ctx) return;',
  '',
  '    const rect = canvas.getBoundingClientRect();',
  '    const width = rect.width;',
  '    const dpr = window.devicePixelRatio || 1;',
  '',
  '    canvas.width = width * dpr;',
  '    canvas.height = height * dpr;',
  '    ctx.scale(dpr, dpr);',
  '',
  '    ctx.clearRect(0, 0, width, height);',
  '',
  '    const isDark = document.documentElement.classList.contains("dark");',
  '    const gridColor = isDark ? "rgba(39, 44, 54, 0.45)" : "rgba(226, 232, 240, 0.8)";',
  '    const textColor = isDark ? "#64748B" : "#94A3B8";',
  '',
  '    const topPadding = 25;',
  '    const bottomPadding = 45;',
  '    const rightPadding = 60;',
  '    const leftPadding = 10;',
  '',
  '    const chartWidth = width - leftPadding - rightPadding;',
  '    const chartHeight = height - topPadding - bottomPadding;',
  '    const volumeHeight = chartHeight * 0.22;',
  '    const priceHeight = chartHeight - volumeHeight - 15;',
  '',
  '    // Calculate min/max price & volume',
  '    const minPrice = Math.min(...data.map(d => d.low));',
  '    const maxPrice = Math.max(...data.map(d => d.high));',
  '    const priceRange = maxPrice - minPrice || 1;',
  '    const maxVolume = Math.max(...data.map(d => d.volume)) || 1;',
  '',
  '    // Horizontal grid lines and price axis labels',
  '    ctx.lineWidth = 0.8;',
  '    ctx.strokeStyle = gridColor;',
  '    ctx.font = "10px Inter, sans-serif";',
  '    ctx.fillStyle = textColor;',
  '    ctx.textAlign = "left";',
  '',
  '    const gridCount = 5;',
  '    for (let i = 0; i <= gridCount; i++) {',
  '      const y = topPadding + (i / gridCount) * priceHeight;',
  '      const priceVal = maxPrice - (i / gridCount) * priceRange;',
  '',
  '      ctx.beginPath();',
  '      ctx.moveTo(leftPadding, y);',
  '      ctx.lineTo(width - rightPadding, y);',
  '      ctx.stroke();',
  '',
  '      ctx.fillText(`₹${priceVal.toFixed(1)}`, width - rightPadding + 8, y + 3);',
  '    }',
  '',
  '    const candleWidth = Math.max(2, (chartWidth / data.length) * 0.7);',
  '    const stepX = chartWidth / data.length;',
  '',
  '    // Draw Volume Bars & Candlesticks / Line',
  '    if (chartType === "line") {',
  '      // Line path',
  '      ctx.beginPath();',
  '      data.forEach((d, i) => {',
  '        const x = leftPadding + i * stepX + stepX / 2;',
  '        const y = topPadding + priceHeight - ((d.close - minPrice) / priceRange) * priceHeight;',
  '        if (i === 0) ctx.moveTo(x, y);',
  '        else ctx.lineTo(x, y);',
  '      });',
  '      ctx.strokeStyle = "#C9A227";',
  '      ctx.lineWidth = 2;',
  '      ctx.stroke();',
  '',
  '      // Gradient fill below',
  '      ctx.lineTo(leftPadding + (data.length - 1) * stepX + stepX / 2, topPadding + priceHeight);',
  '      ctx.lineTo(leftPadding + stepX / 2, topPadding + priceHeight);',
  '      ctx.closePath();',
  '      const grad = ctx.createLinearGradient(0, topPadding, 0, topPadding + priceHeight);',
  '      grad.addColorStop(0, "rgba(201, 162, 39, 0.25)");',
  '      grad.addColorStop(1, "rgba(201, 162, 39, 0.0)");',
  '      ctx.fillStyle = grad;',
  '      ctx.fill();',
  '    } else {',
  '      // Candlesticks',
  '      data.forEach((d, i) => {',
  '        const x = leftPadding + i * stepX + stepX / 2;',
  '        const isGreen = d.close >= d.open;',
  '        const color = isGreen ? "#35C98A" : "#F05D5E";',
  '',
  '        const openY = topPadding + priceHeight - ((d.open - minPrice) / priceRange) * priceHeight;',
  '        const closeY = topPadding + priceHeight - ((d.close - minPrice) / priceRange) * priceHeight;',
  '        const highY = topPadding + priceHeight - ((d.high - minPrice) / priceRange) * priceHeight;',
  '        const lowY = topPadding + priceHeight - ((d.low - minPrice) / priceRange) * priceHeight;',
  '',
  '        // Wick line',
  '        ctx.beginPath();',
  '        ctx.strokeStyle = color;',
  '        ctx.lineWidth = 1.2;',
  '        ctx.moveTo(x, highY);',
  '        ctx.lineTo(x, lowY);',
  '        ctx.stroke();',
  '',
  '        // Candle body',
  '        const bodyY = Math.min(openY, closeY);',
  '        const bodyHeight = Math.max(1.5, Math.abs(closeY - openY));',
  '        ctx.fillStyle = color;',
  '        ctx.fillRect(x - candleWidth / 2, bodyY, candleWidth, bodyHeight);',
  '',
  '        // Volume bar at bottom',
  '        const volBarHeight = (d.volume / maxVolume) * volumeHeight;',
  '        const volY = height - bottomPadding - volBarHeight;',
  '        ctx.fillStyle = isGreen ? "rgba(53, 201, 138, 0.35)" : "rgba(240, 93, 94, 0.35)";',
  '        ctx.fillRect(x - candleWidth / 2, volY, candleWidth, volBarHeight);',
  '      });',
  '    }',
  '',
  '    // Time labels at bottom',
  '    ctx.fillStyle = textColor;',
  '    ctx.textAlign = "center";',
  '    const labelStep = Math.max(1, Math.floor(data.length / 5));',
  '    for (let i = 0; i < data.length; i += labelStep) {',
  '      const x = leftPadding + i * stepX + stepX / 2;',
  '      ctx.fillText(data[i].time, x, height - 12);',
  '    }',
  '',
  '    // Crosshair on hover',
  '    if (hoveredIndex !== null && hoveredIndex >= 0 && hoveredIndex < data.length) {',
  '      const hoverItem = data[hoveredIndex];',
  '      const hx = leftPadding + hoveredIndex * stepX + stepX / 2;',
  '      const hy = topPadding + priceHeight - ((hoverItem.close - minPrice) / priceRange) * priceHeight;',
  '',
  '      ctx.setLineDash([4, 4]);',
  '      ctx.strokeStyle = isDark ? "rgba(255, 255, 255, 0.4)" : "rgba(0, 0, 0, 0.3)";',
  '      ctx.lineWidth = 1;',
  '',
  '      // Vertical line',
  '      ctx.beginPath();',
  '      ctx.moveTo(hx, topPadding);',
  '      ctx.lineTo(hx, height - bottomPadding);',
  '      ctx.stroke();',
  '',
  '      // Horizontal line',
  '      ctx.beginPath();',
  '      ctx.moveTo(leftPadding, hy);',
  '      ctx.lineTo(width - rightPadding, hy);',
  '      ctx.stroke();',
  '      ctx.setLineDash([]);',
  '',
  '      // Price tag on right axis',
  '      ctx.fillStyle = "#C9A227";',
  '      ctx.fillRect(width - rightPadding, hy - 9, rightPadding - 5, 18);',
  '      ctx.fillStyle = "#090A0F";',
  '      ctx.font = "bold 10px Inter, sans-serif";',
  '      ctx.textAlign = "left";',
  '      ctx.fillText(`₹${hoverItem.close.toFixed(1)}`, width - rightPadding + 4, hy + 3.5);',
  '    }',
  '  }, [data, chartType, height, hoveredIndex]);',
  '',
  '  useEffect(() => {',
  '    drawChart();',
  '    const handleResize = () => drawChart();',
  '    window.addEventListener("resize", handleResize);',
  '    return () => window.removeEventListener("resize", handleResize);',
  '  }, [drawChart]);',
  '',
  '  const handleMouseMove = (e: React.MouseEvent<HTMLCanvasElement>) => {',
  '    const canvas = canvasRef.current;',
  '    if (!canvas || !data || data.length === 0) return;',
  '    const rect = canvas.getBoundingClientRect();',
  '    const mouseX = e.clientX - rect.left - 10;',
  '    const chartWidth = rect.width - 70;',
  '    const stepX = chartWidth / data.length;',
  '    const index = Math.floor(mouseX / stepX);',
  '    if (index >= 0 && index < data.length) {',
  '      setHoveredIndex(index);',
  '    } else {',
  '      setHoveredIndex(null)',
  '    }',
  '  };',
  '',
  '  const hoveredData = hoveredIndex !== null && data[hoveredIndex] ? data[hoveredIndex] : data[data.length - 1];',
  '',
  '  return (',
  '    <div ref={containerRef} className={`w-full bg-bg-card rounded-2xl border border-border-subtle p-4 ${className}`}>',
  '      {/* Chart Top Header & Controls */}',
  '      <div className="flex flex-wrap items-center justify-between gap-3 mb-3 border-b border-border-subtle/60 pb-3">',
  '        <div className="flex items-center gap-3">',
  '          <span className="text-sm font-bold text-text-primary tracking-wide">{symbol}</span>',
  '          {hoveredData && (',
  '            <div className="flex items-center gap-3 text-xs">',
  '              <span className="text-text-muted">O: <strong className="text-text-primary">₹{hoveredData.open}</strong></span>',
  '              <span className="text-text-muted">H: <strong className="text-brand-positive">₹{hoveredData.high}</strong></span>',
  '              <span className="text-text-muted">L: <strong className="text-brand-negative">₹{hoveredData.low}</strong></span>',
  '              <span className="text-text-muted">C: <strong className="text-text-primary">₹{hoveredData.close}</strong></span>',
  '              <span className="text-text-muted">Vol: <strong className="text-text-primary">{(hoveredData.volume / 1000).toFixed(1)}k</strong></span>',
  '            </div>',
  '          )}',
  '        </div>',
  '',
  '        <div className="flex items-center gap-2">',
  '          {/* Chart Type Toggle */}',
  '          <div className="flex items-center bg-bg-secondary p-0.5 rounded-lg border border-border-subtle">',
  '            <button',
  '              onClick={() => setChartType("candle")}',
  '              className={`px-2 py-1 text-xs rounded-md transition-colors ${',
  '                chartType === "candle" ? "bg-bg-elevated text-brand-accent font-semibold" : "text-text-secondary"',
  '              }`}',
  '              title="Candlestick Chart"',
  '            >',
  '              <BarChart3 className="w-3.5 h-3.5 inline" />',
  '            </button>',
  '            <button',
  '              onClick={() => setChartType("line")}',
  '              className={`px-2 py-1 text-xs rounded-md transition-colors ${',
  '                chartType === "line" ? "bg-bg-elevated text-brand-accent font-semibold" : "text-text-secondary"',
  '              }`}',
  '              title="Line Chart"',
  '            >',
  '              <TrendingUp className="w-3.5 h-3.5 inline" />',
  '            </button>',
  '          </div>',
  '',
  '          {/* Timeframe Buttons */}',
  '          <div className="flex items-center bg-bg-secondary p-0.5 rounded-lg border border-border-subtle">',
  '            {timeframes.map(tf => (',
  '              <button',
  '                key={tf}',
  '                onClick={() => onTimeframeChange(tf)}',
  '                className={`px-2.5 py-1 text-xs rounded-md transition-colors ${',
  '                  timeframe === tf ? "bg-brand-accent text-bg-primary font-bold shadow-xs" : "text-text-secondary hover:text-text-primary"',
  '                }`}',
  '              >',
  '                {tf}',
  '              </button>',
  '            ))}',
  '          </div>',
  '        </div>',
  '      </div>',
  '',
  '      {/* Interactive HTML5 Canvas */}',
  '      <div className="relative w-full overflow-hidden">',
  '        <canvas',
  '          ref={canvasRef}',
  '          onMouseMove={handleMouseMove}',
  '          onMouseLeave={() => setHoveredIndex(null)}',
  '          className="w-full cursor-crosshair"',
  '          style={{ height }}',
  '        />',
  '      </div>',
  '    </div>',
  '  );',
  '};'
].join('\n'));

// 3. EquityCurveChart.tsx
fs.writeFileSync(path.join(srcDir, 'components/charts/EquityCurveChart.tsx'), [
  'import React, { useEffect, useRef } from "react";',
  '',
  'interface EquityPoint {',
  '  date: string;',
  '  cumulativePnL: number;',
  '  drawdown: number;',
  '}',
  '',
  'interface EquityCurveChartProps {',
  '  data: EquityPoint[];',
  '  height?: number;',
  '  className?: string;',
  '}',
  '',
  'export const EquityCurveChart: React.FC<EquityCurveChartProps> = ({',
  '  data,',
  '  height = 240,',
  '  className = ""',
  '}) => {',
  '  const canvasRef = useRef<HTMLCanvasElement | null>(null);',
  '',
  '  useEffect(() => {',
  '    const canvas = canvasRef.current;',
  '    if (!canvas || !data || data.length === 0) return;',
  '    const ctx = canvas.getContext("2d");',
  '    if (!ctx) return;',
  '',
  '    const rect = canvas.getBoundingClientRect();',
  '    const width = rect.width;',
  '    const dpr = window.devicePixelRatio || 1;',
  '',
  '    canvas.width = width * dpr;',
  '    canvas.height = height * dpr;',
  '    ctx.scale(dpr, dpr);',
  '    ctx.clearRect(0, 0, width, height);',
  '',
  '    const isDark = document.documentElement.classList.contains("dark");',
  '    const gridColor = isDark ? "rgba(39, 44, 54, 0.45)" : "rgba(226, 232, 240, 0.8)";',
  '    const textColor = isDark ? "#64748B" : "#94A3B8";',
  '',
  '    const topPadding = 20;',
  '    const bottomPadding = 30;',
  '    const rightPadding = 65;',
  '    const leftPadding = 15;',
  '',
  '    const chartWidth = width - leftPadding - rightPadding;',
  '    const chartHeight = height - topPadding - bottomPadding;',
  '',
  '    const pnlValues = data.map(d => d.cumulativePnL);',
  '    const minPnL = Math.min(0, ...pnlValues);',
  '    const maxPnL = Math.max(1000, ...pnlValues);',
  '    const range = maxPnL - minPnL || 1;',
  '',
  '    // Zero line',
  '    const zeroY = topPadding + chartHeight - ((0 - minPnL) / range) * chartHeight;',
  '    ctx.strokeStyle = "rgba(201, 162, 39, 0.4)";',
  '    ctx.lineWidth = 1;',
  '    ctx.setLineDash([4, 4]);',
  '    ctx.beginPath();',
  '    ctx.moveTo(leftPadding, zeroY);',
  '    ctx.lineTo(width - rightPadding, zeroY);',
  '    ctx.stroke();',
  '    ctx.setLineDash([]);',
  '',
  '    // Axis labels',
  '    ctx.fillStyle = textColor;',
  '    ctx.font = "10px Inter, sans-serif";',
  '    ctx.textAlign = "left";',
  '    ctx.fillText(`+₹${maxPnL.toLocaleString("en-IN")}`, width - rightPadding + 6, topPadding + 10);',
  '    ctx.fillText(`₹0`, width - rightPadding + 6, zeroY + 3);',
  '    if (minPnL < 0) {',
  '      ctx.fillText(`-₹${Math.abs(minPnL).toLocaleString("en-IN")}`, width - rightPadding + 6, height - bottomPadding);',
  '    }',
  '',
  '    // Plot equity line',
  '    const stepX = chartWidth / (data.length - 1 || 1);',
  '    ctx.beginPath();',
  '    data.forEach((pt, i) => {',
  '      const x = leftPadding + i * stepX;',
  '      const y = topPadding + chartHeight - ((pt.cumulativePnL - minPnL) / range) * chartHeight;',
  '      if (i === 0) ctx.moveTo(x, y);',
  '      else ctx.lineTo(x, y);',
  '    });',
  '',
  '    ctx.strokeStyle = "#35C98A";',
  '    ctx.lineWidth = 2.4;',
  '    ctx.stroke();',
  '',
  '    // Gradient fill below equity line to zero',
  '    ctx.lineTo(leftPadding + (data.length - 1) * stepX, zeroY);',
  '    ctx.lineTo(leftPadding, zeroY);',
  '    ctx.closePath();',
  '    const grad = ctx.createLinearGradient(0, topPadding, 0, height - bottomPadding);',
  '    grad.addColorStop(0, "rgba(53, 201, 138, 0.25)");',
  '    grad.addColorStop(1, "rgba(53, 201, 138, 0.0)");',
  '    ctx.fillStyle = grad;',
  '    ctx.fill();',
  '',
  '    // Date labels',
  '    ctx.fillStyle = textColor;',
  '    ctx.textAlign = "center";',
  '    const labelStep = Math.max(1, Math.floor(data.length / 4));',
  '    for (let i = 0; i < data.length; i += labelStep) {',
  '      const x = leftPadding + i * stepX;',
  '      ctx.fillText(data[i].date.substring(5), x, height - 8);',
  '    }',
  '  }, [data, height]);',
  '',
  '  return (',
  '    <div className={`w-full bg-bg-card rounded-2xl border border-border-subtle p-4 ${className}`}>',
  '      <div className="flex items-center justify-between mb-2">',
  '        <span className="text-xs font-semibold text-text-secondary">Cumulative Net Equity Curve</span>',
  '        <span className="text-xs font-bold text-brand-positive">',
  '          Net P&L: ₹{data.length > 0 ? data[data.length - 1].cumulativePnL.toLocaleString("en-IN") : "0"}',
  '        </span>',
  '      </div>',
  '      <canvas ref={canvasRef} style={{ height }} className="w-full" />',
  '    </div>',
  '  );',
  '};'
].join('\n'));

// 4. PnLDistributionChart.tsx
fs.writeFileSync(path.join(srcDir, 'components/charts/DistributionChart.tsx'), [
  'import React from "react";',
  '',
  'interface DistributionProps {',
  '  winningTrades: number;',
  '  losingTrades: number;',
  '  winRate: number;',
  '  className?: string;',
  '}',
  '',
  'export const DistributionChart: React.FC<DistributionProps> = ({',
  '  winningTrades,',
  '  losingTrades,',
  '  winRate,',
  '  className = ""',
  '}) => {',
  '  const total = winningTrades + losingTrades || 1;',
  '  const winPercent = Math.round((winningTrades / total) * 100);',
  '  const lossPercent = 100 - winPercent;',
  '',
  '  return (',
  '    <div className={`p-4 bg-bg-card rounded-2xl border border-border-subtle ${className}`}>',
  '      <div className="flex items-center justify-between mb-3 text-xs font-medium text-text-secondary">',
  '        <span>Win / Loss Distribution</span>',
  '        <span className="font-bold text-text-primary">{winningTrades} Wins / {losingTrades} Losses</span>',
  '      </div>',
  '      <div className="h-5 flex rounded-xl overflow-hidden border border-border-subtle/80 mb-3">',
  '        <div',
  '          className="bg-brand-positive flex items-center justify-center text-[10px] font-bold text-bg-primary transition-all duration-500"',
  '          style={{ width: `${winPercent}%` }}',
  '        >',
  '          {winPercent > 12 && `${winPercent}%`} ',
  '        </div>',
  '        <div',
  '          className="bg-brand-negative flex items-center justify-center text-[10px] font-bold text-white transition-all duration-500"',
  '          style={{ width: `${lossPercent}%` }}',
  '        >',
  '          {lossPercent > 12 && `${lossPercent}%`} ',
  '        </div>',
  '      </div>',
  '      <div className="flex items-center justify-between text-xs">',
  '        <div className="flex items-center gap-1.5">',
  '          <span className="w-2.5 h-2.5 rounded-full bg-brand-positive" />',
  '          <span className="text-text-secondary">Winning Trades ({winningTrades})</span>',
  '        </div>',
  '        <div className="flex items-center gap-1.5">',
  '          <span className="w-2.5 h-2.5 rounded-full bg-brand-negative" />',
  '          <span className="text-text-secondary">Losing Trades ({losingTrades})</span>',
  '        </div>',
  '      </div>',
  '    </div>',
  '  );',
  '};'
].join('\n'));

console.log('Charts components created successfully');
