const fs = require('fs');
const path = require('path');
const srcDir = path.resolve(__dirname, '..', 'src');

// 1. Card.tsx
fs.writeFileSync(path.join(srcDir, 'components/common/Card.tsx'), [
  'import React from "react";',
  '',
  'interface CardProps extends React.HTMLAttributes<HTMLDivElement> {',
  '  children: React.ReactNode;',
  '  variant?: "default" | "elevated" | "glass" | "bordered";',
  '  className?: string;',
  '}',
  '',
  'export const Card: React.FC<CardProps> = ({',
  '  children,',
  '  variant = "default",',
  '  className = "",',
  '  ...props',
  '}) => {',
  '  let baseClass = "rounded-2xl transition-all duration-200 p-5 ";',
  '  if (variant === "default") {',
  '    baseClass += "bg-bg-card border border-border-subtle shadow-sm ";',
  '  } else if (variant === "elevated") {',
  '    baseClass += "bg-bg-elevated border border-border-subtle/80 shadow-md ";',
  '  } else if (variant === "glass") {',
  '    baseClass += "glass-panel shadow-glass ";',
  '  } else if (variant === "bordered") {',
  '    baseClass += "bg-transparent border border-border-subtle ";',
  '  }',
  '',
  '  return (',
  '    <div className={`${baseClass} ${className}`} {...props}>',
  '      {children}',
  '    </div>',
  '  );',
  '};'
].join('\n'));

// 2. Button.tsx
fs.writeFileSync(path.join(srcDir, 'components/common/Button.tsx'), [
  'import React from "react";',
  '',
  'interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {',
  '  variant?: "primary" | "secondary" | "outline" | "danger" | "success" | "ghost";',
  '  size?: "sm" | "md" | "lg";',
  '  icon?: React.ReactNode;',
  '  children: React.ReactNode;',
  '  className?: string;',
  '}',
  '',
  'export const Button: React.FC<ButtonProps> = ({',
  '  variant = "primary",',
  '  size = "md",',
  '  icon,',
  '  children,',
  '  className = "",',
  '  disabled,',
  '  ...props',
  '}) => {',
  '  let base = "inline-flex items-center justify-center font-medium rounded-xl transition-all duration-200 select-none active:scale-[0.98] disabled:opacity-50 disabled:pointer-events-none ";',
  '',
  '  // Size',
  '  if (size === "sm") base += "px-3 py-1.5 text-xs gap-1.5 ";',
  '  else if (size === "md") base += "px-4 py-2.5 text-sm gap-2 ";',
  '  else if (size === "lg") base += "px-6 py-3.5 text-base gap-2.5 ";',
  '',
  '  // Variant',
  '  if (variant === "primary") {',
  '    base += "bg-brand-accent text-bg-primary hover:bg-brand-accentHover shadow-sm font-semibold ";',
  '  } else if (variant === "secondary") {',
  '    base += "bg-bg-elevated text-text-primary hover:bg-border-subtle border border-border-subtle ";',
  '  } else if (variant === "outline") {',
  '    base += "bg-transparent text-text-primary border border-border-subtle hover:border-brand-accent/60 hover:text-brand-accent ";',
  '  } else if (variant === "danger") {',
  '    base += "bg-brand-negative/15 text-brand-negative hover:bg-brand-negative/25 border border-brand-negative/30 font-medium ";',
  '  } else if (variant === "success") {',
  '    base += "bg-brand-positive/15 text-brand-positive hover:bg-brand-positive/25 border border-brand-positive/30 font-medium ";',
  '  } else if (variant === "ghost") {',
  '    base += "bg-transparent text-text-secondary hover:text-text-primary hover:bg-bg-elevated/60 ";',
  '  }',
  '',
  '  return (',
  '    <button className={`${base} ${className}`} disabled={disabled} {...props}>',
  '      {icon && <span className="flex-shrink-0">{icon}</span>}',
  '      <span>{children}</span>',
  '    </button>',
  '  );',
  '};'
].join('\n'));

// 3. Badge.tsx
fs.writeFileSync(path.join(srcDir, 'components/common/Badge.tsx'), [
  'import React from "react";',
  '',
  'interface BadgeProps {',
  '  variant?: "positive" | "negative" | "warning" | "accent" | "neutral" | "info";',
  '  size?: "sm" | "md";',
  '  children: React.ReactNode;',
  '  className?: string;',
  '  dot?: boolean;',
  '}',
  '',
  'export const Badge: React.FC<BadgeProps> = ({',
  '  variant = "neutral",',
  '  size = "md",',
  '  children,',
  '  className = "",',
  '  dot = false',
  '}) => {',
  '  let base = "inline-flex items-center font-medium rounded-lg border ";',
  '  if (size === "sm") base += "px-2 py-0.5 text-[11px] gap-1 ";',
  '  else base += "px-2.5 py-1 text-xs gap-1.5 ";',
  '',
  '  let dotColor = "";',
  '  if (variant === "positive") {',
  '    base += "bg-brand-positive/10 text-brand-positive border-brand-positive/20 ";',
  '    dotColor = "bg-brand-positive";',
  '  } else if (variant === "negative") {',
  '    base += "bg-brand-negative/10 text-brand-negative border-brand-negative/20 ";',
  '    dotColor = "bg-brand-negative";',
  '  } else if (variant === "warning") {',
  '    base += "bg-brand-warning/10 text-brand-warning border-brand-warning/20 ";',
  '    dotColor = "bg-brand-warning";',
  '  } else if (variant === "accent") {',
  '    base += "bg-brand-accent/10 text-brand-accent border-brand-accent/25 ";',
  '    dotColor = "bg-brand-accent";',
  '  } else if (variant === "info") {',
  '    base += "bg-blue-500/10 text-blue-400 border-blue-500/20 ";',
  '    dotColor = "bg-blue-400";',
  '  } else {',
  '    base += "bg-bg-elevated text-text-secondary border-border-subtle ";',
  '    dotColor = "bg-text-muted";',
  '  }',
  '',
  '  return (',
  '    <span className={`${base} ${className}`}>',
  '      {dot && <span className={`w-1.5 h-1.5 rounded-full ${dotColor} animate-pulse`} />}',
  '      <span>{children}</span>',
  '    </span>',
  '  );',
  '};'
].join('\n'));

// 4. Modal.tsx
fs.writeFileSync(path.join(srcDir, 'components/common/Modal.tsx'), [
  'import React, { useEffect } from "react";',
  'import { X } from "lucide-react";',
  '',
  'interface ModalProps {',
  '  isOpen: boolean;',
  '  onClose: () => void;',
  '  title?: React.ReactNode;',
  '  subtitle?: string;',
  '  children: React.ReactNode;',
  '  maxWidth?: "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | "4xl";',
  '}',
  '',
  'export const Modal: React.FC<ModalProps> = ({',
  '  isOpen,',
  '  onClose,',
  '  title,',
  '  subtitle,',
  '  children,',
  '  maxWidth = "lg"',
  '}) => {',
  '  useEffect(() => {',
  '    const handleKeyDown = (e: KeyboardEvent) => {',
  '      if (e.key === "Escape") onClose();',
  '    };',
  '    if (isOpen) {',
  '      document.body.style.overflow = "hidden";',
  '      window.addEventListener("keydown", handleKeyDown);',
  '    }',
  '    return () => {',
  '      document.body.style.overflow = "unset";',
  '      window.removeEventListener("keydown", handleKeyDown);',
  '    };',
  '  }, [isOpen, onClose]);',
  '',
  '  if (!isOpen) return null;',
  '',
  '  let maxWidthClass = "max-w-lg";',
  '  if (maxWidth === "sm") maxWidthClass = "max-w-sm";',
  '  else if (maxWidth === "md") maxWidthClass = "max-w-md";',
  '  else if (maxWidth === "lg") maxWidthClass = "max-w-lg";',
  '  else if (maxWidth === "xl") maxWidthClass = "max-w-xl";',
  '  else if (maxWidth === "2xl") maxWidthClass = "max-w-2xl";',
  '  else if (maxWidth === "3xl") maxWidthClass = "max-w-3xl";',
  '  else if (maxWidth === "4xl") maxWidthClass = "max-w-4xl";',
  '',
  '  return (',
  '    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 animate-fadeIn">',
  '      {/* Backdrop */}',
  '      <div',
  '        className="fixed inset-0 bg-black/75 backdrop-blur-sm transition-opacity"',
  '        onClick={onClose}',
  '      />',
  '',
  '      {/* Content */}',
  '      <div className={`relative w-full ${maxWidthClass} max-h-[90vh] flex flex-col bg-bg-card border border-border-subtle rounded-3xl shadow-2xl overflow-hidden z-10 animate-scaleUp`}>',
  '        {(title || subtitle) && (',
  '          <div className="flex items-center justify-between px-6 py-5 border-b border-border-subtle bg-bg-card/50">',
  '            <div>',
  '              {typeof title === "string" ? (',
  '                <h3 className="text-lg font-semibold text-text-primary">{title}</h3>',
  '              ) : (',
  '                title',
  '              )}',
  '              {subtitle && <p className="text-xs text-text-secondary mt-0.5">{subtitle}</p>}',
  '            </div>',
  '            <button',
  '              onClick={onClose}',
  '              className="p-2 rounded-xl text-text-secondary hover:text-text-primary hover:bg-bg-elevated transition-colors"',
  '              aria-label="Close dialog"',
  '            >',
  '              <X className="w-5 h-5" />',
  '            </button>',
  '          </div>',
  '        )}',
  '        <div className="flex-1 overflow-y-auto p-6 custom-scrollbar">{children}</div>',
  '      </div>',
  '    </div>',
  '  );',
  '};'
].join('\n'));

// 5. ProgressBar.tsx
fs.writeFileSync(path.join(srcDir, 'components/common/ProgressBar.tsx'), [
  'import React from "react";',
  '',
  'interface ProgressBarProps {',
  '  value: number;',
  '  max?: number;',
  '  variant?: "positive" | "negative" | "warning" | "accent" | "dynamic";',
  '  size?: "sm" | "md" | "lg";',
  '  label?: string;',
  '  showValue?: boolean;',
  '  className?: string;',
  '}',
  '',
  'export const ProgressBar: React.FC<ProgressBarProps> = ({',
  '  value,',
  '  max = 100,',
  '  variant = "accent",',
  '  size = "md",',
  '  label,',
  '  showValue = false,',
  '  className = ""',
  '}) => {',
  '  const percentage = Math.min(100, Math.max(0, (value / max) * 100));',
  '',
  '  let heightClass = "h-2";',
  '  if (size === "sm") heightClass = "h-1.5";',
  '  else if (size === "lg") heightClass = "h-3.5";',
  '',
  '  let barColor = "bg-brand-accent";',
  '  if (variant === "positive") barColor = "bg-brand-positive";',
  '  else if (variant === "negative") barColor = "bg-brand-negative";',
  '  else if (variant === "warning") barColor = "bg-brand-warning";',
  '  else if (variant === "dynamic") {',
  '    if (percentage > 80) barColor = "bg-brand-negative";',
  '    else if (percentage > 50) barColor = "bg-brand-warning";',
  '    else barColor = "bg-brand-positive";',
  '  }',
  '',
  '  return (',
  '    <div className={`w-full ${className}`}>',
  '      {(label || showValue) && (',
  '        <div className="flex items-center justify-between text-xs text-text-secondary mb-1.5">',
  '          {label && <span>{label}</span>}',
  '          {showValue && <span className="font-semibold text-text-primary">{Math.round(percentage)}%</span>}',
  '        </div>',
  '      )}',
  '      <div className={`w-full bg-bg-elevated rounded-full overflow-hidden border border-border-subtle/50 ${heightClass}`}>',
  '        <div',
  '          className={`${barColor} ${heightClass} rounded-full transition-all duration-500 ease-out`}',
  '          style={{ width: `${percentage}%` }}',
  '        />',
  '      </div>',
  '    </div>',
  '  );',
  '};'
].join('\n'));

// 6. Tabs.tsx
fs.writeFileSync(path.join(srcDir, 'components/common/Tabs.tsx'), [
  'import React from "react";',
  '',
  'interface TabItem {',
  '  id: string;',
  '  label: string;',
  '  icon?: React.ReactNode;',
  '  count?: number;',
  '}',
  '',
  'interface TabsProps {',
  '  tabs: TabItem[];',
  '  activeTab: string;',
  '  onChange: (id: string) => void;',
  '  className?: string;',
  '}',
  '',
  'export const Tabs: React.FC<TabsProps> = ({ tabs, activeTab, onChange, className = "" }) => {',
  '  return (',
  '    <div className={`flex items-center gap-1.5 p-1 bg-bg-secondary border border-border-subtle rounded-2xl overflow-x-auto ${className}`}>',
  '      {tabs.map(tab => {',
  '        const isActive = activeTab === tab.id;',
  '        return (',
  '          <button',
  '            key={tab.id}',
  '            onClick={() => onChange(tab.id)}',
  '            className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs sm:text-sm font-medium transition-all duration-200 whitespace-nowrap ${',
  '              isActive',
  '                ? "bg-bg-elevated text-text-primary shadow-sm border border-border-subtle/80 font-semibold"',
  '                : "text-text-secondary hover:text-text-primary hover:bg-bg-elevated/40"',
  '            }`}',
  '          >',
  '            {tab.icon && <span>{tab.icon}</span>}',
  '            <span>{tab.label}</span>',
  '            {tab.count !== undefined && (',
  '              <span',
  '                className={`px-1.5 py-0.2 text-[10px] rounded-md ${',
  '                  isActive ? "bg-brand-accent/20 text-brand-accent" : "bg-bg-elevated text-text-muted"',
  '                }`}',
  '              >',
  '                {tab.count}',
  '              </span>',
  '            )}',
  '          </button>',
  '        );',
  '      })}',
  '    </div>',
  '  );',
  '};'
].join('\n'));

// 7. Input.tsx & Select.tsx
fs.writeFileSync(path.join(srcDir, 'components/common/Input.tsx'), [
  'import React from "react";',
  '',
  'interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {',
  '  label?: string;',
  '  helperText?: string;',
  '  error?: string;',
  '  prefixNode?: React.ReactNode;',
  '  suffixNode?: React.ReactNode;',
  '}',
  '',
  'export const Input: React.FC<InputProps> = ({',
  '  label,',
  '  helperText,',
  '  error,',
  '  prefixNode,',
  '  suffixNode,',
  '  className = "",',
  '  ...props',
  '}) => {',
  '  return (',
  '    <div className="w-full">',
  '      {label && <label className="block text-xs font-medium text-text-secondary mb-1.5">{label}</label>}',
  '      <div className="relative flex items-center">',
  '        {prefixNode && (',
  '          <div className="absolute left-3.5 flex items-center text-text-secondary pointer-events-none">',
  '            {prefixNode}',
  '          </div>',
  '        )}',
  '        <input',
  '          className={`w-full bg-bg-secondary border rounded-xl py-2.5 text-sm text-text-primary placeholder:text-text-muted focus:outline-none focus:ring-1 focus:ring-brand-accent focus:border-brand-accent transition-colors ${',
  '            prefixNode ? "pl-10 " : "pl-3.5 "',
  '          }${suffixNode ? "pr-10 " : "pr-3.5 "}${',
  '            error ? "border-brand-negative " : "border-border-subtle "',
  '          }${className}`}',
  '          {...props}',
  '        />',
  '        {suffixNode && (',
  '          <div className="absolute right-3.5 flex items-center text-text-secondary pointer-events-none">',
  '            {suffixNode}',
  '          </div>',
  '        )}',
  '      </div>',
  '      {error ? (',
  '        <p className="text-[11px] text-brand-negative mt-1 font-medium">{error}</p>',
  '      ) : helperText ? (',
  '        <p className="text-[11px] text-text-muted mt-1">{helperText}</p>',
  '      ) : null}',
  '    </div>',
  '  );',
  '};'
].join('\n'));

fs.writeFileSync(path.join(srcDir, 'components/common/Select.tsx'), [
  'import React from "react";',
  '',
  'interface SelectProps extends React.SelectHTMLAttributes<HTMLSelectElement> {',
  '  label?: string;',
  '  options: { value: string; label: string }[];',
  '  error?: string;',
  '  helperText?: string;',
  '}',
  '',
  'export const Select: React.FC<SelectProps> = ({',
  '  label,',
  '  options,',
  '  error,',
  '  helperText,',
  '  className = "",',
  '  ...props',
  '}) => {',
  '  return (',
  '    <div className="w-full">',
  '      {label && <label className="block text-xs font-medium text-text-secondary mb-1.5">{label}</label>}',
  '      <select',
  '        className={`w-full bg-bg-secondary border rounded-xl px-3.5 py-2.5 text-sm text-text-primary focus:outline-none focus:ring-1 focus:ring-brand-accent focus:border-brand-accent transition-colors ${',
  '          error ? "border-brand-negative " : "border-border-subtle "',
  '        }${className}`}',
  '        {...props}',
  '      >',
  '        {options.map(opt => (',
  '          <option key={opt.value} value={opt.value} className="bg-bg-card text-text-primary">',
  '            {opt.label}',
  '          </option>',
  '        ))}',
  '      </select>',
  '      {error ? (',
  '        <p className="text-[11px] text-brand-negative mt-1 font-medium">{error}</p>',
  '      ) : helperText ? (',
  '        <p className="text-[11px] text-text-muted mt-1">{helperText}</p>',
  '      ) : null}',
  '    </div>',
  '  );',
  '};'
].join('\n'));

// 8. StatCard.tsx
fs.writeFileSync(path.join(srcDir, 'components/common/StatCard.tsx'), [
  'import React from "react";',
  'import { Card } from "./Card";',
  '',
  'interface StatCardProps {',
  '  title: string;',
  '  value: React.ReactNode;',
  '  subtitle?: string;',
  '  icon?: React.ReactNode;',
  '  trend?: {',
  '    value: number | string;',
  '    isPositive: boolean;',
  '    label?: string;',
  '  };',
  '  className?: string;',
  '}',
  '',
  'export const StatCard: React.FC<StatCardProps> = ({',
  '  title,',
  '  value,',
  '  subtitle,',
  '  icon,',
  '  trend,',
  '  className = ""',
  '}) => {',
  '  return (',
  '    <Card className={`flex flex-col justify-between ${className}`}>',
  '      <div className="flex items-center justify-between mb-2">',
  '        <span className="text-xs font-medium text-text-secondary">{title}</span>',
  '        {icon && <div className="p-2 rounded-xl bg-bg-elevated text-brand-accent">{icon}</div>}',
  '      </div>',
  '      <div>',
  '        <div className="text-2xl font-bold tracking-tight text-text-primary">{value}</div>',
  '        <div className="flex items-center gap-2 mt-1.5">',
  '          {trend && (',
  '            <span',
  '              className={`text-xs font-semibold px-1.5 py-0.5 rounded ${',
  '                trend.isPositive ? "text-brand-positive bg-brand-positive/10" : "text-brand-negative bg-brand-negative/10"',
  '              }`}',
  '            >',
  '              {trend.isPositive ? "+" : ""}{trend.value}%',
  '            </span>',
  '          )}',
  '          {subtitle && <span className="text-xs text-text-muted truncate">{subtitle}</span>}',
  '        </div>',
  '      </div>',
  '    </Card>',
  '  );',
  '};'
].join('\n'));

// 9. EmptyState.tsx
fs.writeFileSync(path.join(srcDir, 'components/common/EmptyState.tsx'), [
  'import React from "react";',
  'import { Button } from "./Button";',
  '',
  'interface EmptyStateProps {',
  '  icon: React.ReactNode;',
  '  title: string;',
  '  description: string;',
  '  actionLabel?: string;',
  '  onAction?: () => void;',
  '  className?: string;',
  '}',
  '',
  'export const EmptyState: React.FC<EmptyStateProps> = ({',
  '  icon,',
  '  title,',
  '  description,',
  '  actionLabel,',
  '  onAction,',
  '  className = ""',
  '}) => {',
  '  return (',
  '    <div className={`flex flex-col items-center justify-center p-8 text-center bg-bg-card/40 border border-dashed border-border-subtle rounded-3xl ${className}`}>',
  '      <div className="p-4 bg-bg-elevated rounded-2xl text-brand-accent mb-3.5 shadow-sm">',
  '        {icon}',
  '      </div>',
  '      <h4 className="text-base font-semibold text-text-primary mb-1">{title}</h4>',
  '      <p className="text-xs text-text-secondary max-w-sm mb-5 leading-relaxed">{description}</p>',
  '      {actionLabel && onAction && (',
  '        <Button variant="primary" size="sm" onClick={onAction}>',
  '          {actionLabel}',
  '        </Button>',
  '      )}',
  '    </div>',
  '  );',
  '};'
].join('\n'));

// 10. DisciplineGauge.tsx
fs.writeFileSync(path.join(srcDir, 'components/common/DisciplineGauge.tsx'), [
  'import React from "react";',
  'import { DisciplineMetrics } from "../../types";',
  'import { ShieldCheck, Target, AlertTriangle, HeartHandshake, Zap } from "lucide-react";',
  '',
  'interface DisciplineGaugeProps {',
  '  metrics: DisciplineMetrics;',
  '  className?: string;',
  '}',
  '',
  'export const DisciplineGauge: React.FC<DisciplineGaugeProps> = ({ metrics, className = "" }) => {',
  '  const score = metrics.overallScore;',
  '  const radius = 58;',
  '  const circumference = 2 * Math.PI * radius;',
  '  const strokeDashoffset = circumference - (score / 100) * circumference;',
  '',
  '  let scoreColor = "#35C98A";',
  '  let scoreBadge = "Disciplined Master";',
  '  if (score < 60) {',
  '    scoreColor = "#F05D5E";',
  '    scoreBadge = "Needs Review";',
  '  } else if (score < 80) {',
  '    scoreColor = "#F2B84B";',
  '    scoreBadge = "Developing Process";',
  '  }',
  '',
  '  const pillars = [',
  '    { label: "Risk Management", score: metrics.riskManagementScore, icon: <ShieldCheck className="w-4 h-4 text-brand-accent" /> },',
  '    { label: "Plan Adherence", score: metrics.planAdherenceScore, icon: <Target className="w-4 h-4 text-brand-positive" /> },',
  '    { label: "Stop Loss Discipline", score: metrics.stopLossDisciplineScore, icon: <AlertTriangle className="w-4 h-4 text-blue-400" /> },',
  '    { label: "Overtrading Control", score: metrics.overtradingControlScore, icon: <Zap className="w-4 h-4 text-purple-400" /> },',
  '    { label: "Emotional Control", score: metrics.emotionalControlScore, icon: <HeartHandshake className="w-4 h-4 text-brand-warning" /> }',
  '  ];',
  '',
  '  return (',
  '    <div className={`flex flex-col md:flex-row items-center gap-6 ${className}`}>',
  '      {/* Circular Ring Gauge */}',
  '      <div className="relative flex flex-col items-center justify-center flex-shrink-0">',
  '        <svg className="w-36 h-36 transform -rotate-90">',
  '          <circle',
  '            cx="72"',
  '            cy="72"',
  '            r={radius}',
  '            className="text-border-subtle/60"',
  '            strokeWidth="10"',
  '            stroke="currentColor"',
  '            fill="transparent"',
  '          />',
  '          <circle',
  '            cx="72"',
  '            cy="72"',
  '            r={radius}',
  '            stroke={scoreColor}',
  '            strokeWidth="10"',
  '            strokeDasharray={circumference}',
  '            strokeDashoffset={strokeDashoffset}',
  '            strokeLinecap="round"',
  '            fill="transparent"',
  '            className="transition-all duration-1000 ease-out"',
  '          />',
  '        </svg>',
  '        <div className="absolute inset-0 flex flex-col items-center justify-center text-center">',
  '          <span className="text-3xl font-extrabold text-text-primary tracking-tight">{score}</span>',
  '          <span className="text-[11px] font-semibold text-text-muted uppercase tracking-wider">/ 100</span>',
  '        </div>',
  '        <span className="mt-2 text-xs font-semibold px-2.5 py-0.5 rounded-full border border-border-subtle bg-bg-elevated text-text-primary">',
  '          {scoreBadge}',
  '        </span>',
  '      </div>',
  '',
  '      {/* 5-Factor Pillars Breakdown */}',
  '      <div className="flex-1 w-full grid grid-cols-1 sm:grid-cols-2 gap-3">',
  '        {pillars.map((pillar, idx) => (',
  '          <div key={idx} className="flex items-center justify-between p-2.5 rounded-xl bg-bg-secondary border border-border-subtle/70">',
  '            <div className="flex items-center gap-2">',
  '              {pillar.icon}',
  '              <span className="text-xs font-medium text-text-secondary">{pillar.label}</span>',
  '            </div>',
  '            <div className="flex items-center gap-2">',
  '              <div className="w-16 h-1.5 bg-bg-elevated rounded-full overflow-hidden">',
  '                <div',
  '                  className="h-full bg-brand-accent rounded-full transition-all duration-500"',
  '                  style={{ width: `${pillar.score}%` }}',
  '                />',
  '              </div>',
  '              <span className="text-xs font-bold text-text-primary w-7 text-right">{pillar.score}%</span>',
  '            </div>',
  '          </div>',
  '        ))}',
  '      </div>',
  '    </div>',
  '  );',
  '};'
].join('\n'));

// 11. RiskVisualizer.tsx
fs.writeFileSync(path.join(srcDir, 'components/common/RiskVisualizer.tsx'), [
  'import React from "react";',
  '',
  'interface RiskVisualizerProps {',
  '  entry: number;',
  '  stopLoss: number;',
  '  target: number;',
  '  direction: "BUY" | "SELL";',
  '  className?: string;',
  '}',
  '',
  'export const RiskVisualizer: React.FC<RiskVisualizerProps> = ({',
  '  entry,',
  '  stopLoss,',
  '  target,',
  '  direction,',
  '  className = ""',
  '}) => {',
  '  if (entry <= 0 || stopLoss <= 0 || target <= 0) return null;',
  '',
  '  const risk = Math.abs(entry - stopLoss);',
  '  const reward = Math.abs(target - entry);',
  '  const total = risk + reward;',
  '  const riskPercent = total > 0 ? (risk / total) * 100 : 33;',
  '  const rewardPercent = total > 0 ? (reward / total) * 100 : 67;',
  '  const rrRatio = risk > 0 ? (reward / risk).toFixed(2) : "0";',
  '',
  '  return (',
  '    <div className={`p-4 bg-bg-secondary rounded-2xl border border-border-subtle ${className}`}>',
  '      <div className="flex items-center justify-between text-xs font-medium text-text-secondary mb-2">',
  '        <span>Risk Zone: ₹{risk.toFixed(2)} / share</span>',
  '        <span className="font-bold text-brand-accent">R:R = 1 : {rrRatio}</span>',
  '        <span>Reward Zone: ₹{reward.toFixed(2)} / share</span>',
  '      </div>',
  '      <div className="relative h-6 flex rounded-xl overflow-hidden border border-border-subtle/80 shadow-inner">',
  '        {/* Risk Zone */}',
  '        <div',
  '          className="bg-brand-negative/30 border-r-2 border-brand-negative flex items-center justify-center text-[10px] font-bold text-brand-negative transition-all"',
  '          style={{ width: `${riskPercent}%` }}',
  '        >',
  '          SL: ₹{stopLoss}',
  '        </div>',
  '        {/* Reward Zone */}',
  '        <div',
  '          className="bg-brand-positive/30 flex items-center justify-center text-[10px] font-bold text-brand-positive transition-all"',
  '          style={{ width: `${rewardPercent}%` }}',
  '        >',
  '          Target: ₹{target}',
  '        </div>',
  '      </div>',
  '      <div className="flex items-center justify-between text-[11px] text-text-muted mt-1.5">',
  '        <span>Stop Loss ({direction === "BUY" ? "Below" : "Above"})</span>',
  '        <span className="font-semibold text-text-primary">Entry Trigger: ₹{entry}</span>',
  '        <span>Take Profit Target</span>',
  '      </div>',
  '    </div>',
  '  );',
  '};'
].join('\n'));

console.log('UI common components created successfully');
