const fs = require('fs');
const path = require('path');
const srcDir = path.resolve(__dirname, '..', 'src');

// 1. Sidebar.tsx
fs.writeFileSync(path.join(srcDir, 'components/layout/Sidebar.tsx'), [
  'import React from "react";',
  'import {',
  '  LayoutDashboard,',
  '  TrendingUp,',
  '  Calculator,',
  '  Briefcase,',
  '  BookOpen,',
  '  LineChart,',
  '  GraduationCap,',
  '  HeartHandshake,',
  '  Settings,',
  '  ShieldAlert,',
  '  Sparkles,',
  '  Bookmark',
  '} from "lucide-react";',
  'import { useApp } from "../../context/AppContext";',
  '',
  'export const Sidebar: React.FC = () => {',
  '  const { activeTab, setActiveTab, discipline, journal, paperPositions, academyLessons } = useApp();',
  '',
  '  const unreadLessons = academyLessons.filter(l => !l.isCompleted).length;',
  '  const openTradesCount = journal.filter(t => t.status === "OPEN").length;',
  '',
  '  const mainNavItems = [',
  '    { id: "dashboard", label: "Dashboard", icon: <LayoutDashboard className="w-4 h-4" /> },',
  '    { id: "markets", label: "Markets", icon: <TrendingUp className="w-4 h-4" /> },',
  '    { id: "watchlist", label: "Watchlist", icon: <Bookmark className="w-4 h-4" /> },',
  '    { id: "planner", label: "Trade Planner", icon: <Calculator className="w-4 h-4" /> },',
  '    {',
  '      id: "paper",',
  '      label: "Paper Trading",',
  '      icon: <Briefcase className="w-4 h-4" />,',
  '      badge: paperPositions.length > 0 ? `${paperPositions.length} open` : undefined',
  '    },',
  '    {',
  '      id: "journal",',
  '      label: "Journal",',
  '      icon: <BookOpen className="w-4 h-4" />,',
  '      badge: openTradesCount > 0 ? `${openTradesCount} active` : undefined',
  '    },',
  '    { id: "psychology", label: "Psychology", icon: <HeartHandshake className="w-4 h-4" /> },',
  '    { id: "analytics", label: "Analytics", icon: <LineChart className="w-4 h-4" /> },',
  '    {',
  '      id: "academy",',
  '      label: "Academy",',
  '      icon: <GraduationCap className="w-4 h-4" />,',
  '      badge: unreadLessons > 0 ? `${unreadLessons} left` : undefined',
  '    }',
  '  ];',
  '',
  '  const secondaryNavItems = [',
  '    { id: "settings", label: "Settings", icon: <Settings className="w-4 h-4" /> }',
  '  ];',
  '',
  '  return (',
  '    <aside className="hidden md:flex flex-col w-64 bg-bg-secondary border-r border-border-subtle h-screen sticky top-0 z-30 select-none">',
  '      {/* Logo Brand Header */}',
  '      <div className="flex items-center gap-3 px-6 py-5 border-b border-border-subtle/80">',
  '        <div className="w-9 h-9 rounded-xl bg-brand-accent/15 border border-brand-accent/30 flex items-center justify-center text-brand-accent shadow-sm">',
  '          <TrendingUp className="w-5 h-5 text-brand-accent" />',
  '        </div>',
  '        <div>',
  '          <h1 className="text-base font-bold text-text-primary tracking-wider flex items-center gap-1.5">',
  '            TRADEWISE',
  '            <span className="text-[10px] px-1.5 py-0.5 rounded bg-brand-accent/20 text-brand-accent font-semibold uppercase">',
  '              Pro',
  '            </span>',
  '          </h1>',
  '          <p className="text-[11px] text-text-muted">Discipline & Companion</p>',
  '        </div>',
  '      </div>',
  '',
  '      {/* Main Navigation Links */}',
  '      <div className="flex-1 overflow-y-auto px-3 py-4 space-y-1 custom-scrollbar">',
  '        <div className="px-3 pb-2 text-[10px] font-bold text-text-muted uppercase tracking-wider">',
  '          Core Modules',
  '        </div>',
  '        {mainNavItems.map(item => {',
  '          const isActive = activeTab === item.id;',
  '          return (',
  '            <button',
  '              key={item.id}',
  '              onClick={() => setActiveTab(item.id)}',
  '              className={`w-full flex items-center justify-between px-3.5 py-2.5 rounded-xl text-sm font-medium transition-all duration-150 ${',
  '                isActive',
  '                  ? "bg-bg-elevated text-text-primary border border-border-subtle shadow-sm font-semibold text-brand-accent"',
  '                  : "text-text-secondary hover:text-text-primary hover:bg-bg-card/70"',
  '              }`}',
  '            >',
  '              <div className="flex items-center gap-3">',
  '                <span className={isActive ? "text-brand-accent" : "text-text-muted"}>{item.icon}</span>',
  '                <span>{item.label}</span>',
  '              </div>',
  '              {item.badge && (',
  '                <span className="px-2 py-0.5 text-[10px] rounded-full bg-brand-accent/15 text-brand-accent font-semibold">',
  '                  {item.badge}',
  '                </span>',
  '              )}',
  '            </button>',
  '          );',
  '        })}',
  '',
  '        <div className="pt-4 px-3 pb-2 text-[10px] font-bold text-text-muted uppercase tracking-wider">',
  '          System',
  '        </div>',
  '        {secondaryNavItems.map(item => {',
  '          const isActive = activeTab === item.id;',
  '          return (',
  '            <button',
  '              key={item.id}',
  '              onClick={() => setActiveTab(item.id)}',
  '              className={`w-full flex items-center justify-between px-3.5 py-2.5 rounded-xl text-sm font-medium transition-all duration-150 ${',
  '                isActive',
  '                  ? "bg-bg-elevated text-text-primary border border-border-subtle shadow-sm font-semibold text-brand-accent"',
  '                  : "text-text-secondary hover:text-text-primary hover:bg-bg-card/70"',
  '              }`}',
  '            >',
  '              <div className="flex items-center gap-3">',
  '                <span className={isActive ? "text-brand-accent" : "text-text-muted"}>{item.icon}</span>',
  '                <span>{item.label}</span>',
  '              </div>',
  '            </button>',
  '          );',
  '        })}',
  '      </div>',
  '',
  '      {/* Bottom Mini Discipline Card */}',
  '      <div className="p-4 border-t border-border-subtle/80 bg-bg-card/50 m-3 rounded-2xl border">',
  '        <div className="flex items-center justify-between mb-1.5">',
  '          <span className="text-xs font-semibold text-text-secondary">Discipline Score</span>',
  '          <span className="text-xs font-bold text-brand-positive">{discipline.overallScore}/100</span>',
  '        </div>',
  '        <div className="w-full bg-bg-secondary h-1.5 rounded-full overflow-hidden mb-2">',
  '          <div',
  '            className="bg-brand-positive h-full rounded-full transition-all duration-500"',
  '            style={{ width: `${discipline.overallScore}%` }}',
  '          />',
  '        </div>',
  '        <p className="text-[11px] text-text-muted leading-tight">',
  '          Process > Profits. Stick to your risk rules today.',
  '        </p>',
  '      </div>',
  '    </aside>',
  '  );',
  '};'
].join('\n'));

// 2. Header.tsx
fs.writeFileSync(path.join(srcDir, 'components/layout/Header.tsx'), [
  'import React, { useState, useEffect } from "react";',
  'import {',
  '  Search,',
  '  Sun,',
  '  Moon,',
  '  Plus,',
  '  Clock,',
  '  TrendingUp,',
  '  CheckCircle2,',
  '  AlertCircle',
  '} from "lucide-react";',
  'import { useTheme } from "../../context/ThemeContext";',
  'import { useMarketData } from "../../context/MarketDataContext";',
  'import { useApp } from "../../context/AppContext";',
  'import { Badge } from "../common/Badge";',
  'import { Button } from "../common/Button";',
  '',
  'export const Header: React.FC = () => {',
  '  const { theme, toggleTheme } = useTheme();',
  '  const { marketStatus, quotes, openStockModal } = useMarketData();',
  '  const { setIsNewTradeModalOpen, setActiveTab } = useApp();',
  '',
  '  const [istTime, setIstTime] = useState("");',
  '  const [searchQuery, setSearchQuery] = useState("");',
  '  const [searchResults, setSearchResults] = useState<typeof quotes>([]);',
  '  const [isSearchOpen, setIsSearchOpen] = useState(false);',
  '',
  '  useEffect(() => {',
  '    const updateTime = () => {',
  '      const now = new Date();',
  '      const utc = now.getTime() + now.getTimezoneOffset() * 60000;',
  '      const ist = new Date(utc + 3600000 * 5.5);',
  '      setIstTime(',
  '        ist.toLocaleTimeString("en-IN", {',
  '          hour: "2-digit",',
  '          minute: "2-digit",',
  '          second: "2-digit",',
  '          hour12: true',
  '        }) + " IST"',
  '      );',
  '    };',
  '    updateTime();',
  '    const timer = setInterval(updateTime, 1000);',
  '    return () => clearInterval(timer);',
  '  }, []);',
  '',
  '  useEffect(() => {',
  '    if (!searchQuery.trim()) {',
  '      setSearchResults([]);',
  '      return;',
  '    }',
  '    const q = searchQuery.toLowerCase().trim();',
  '    const filtered = quotes.filter(',
  '      s => s.symbol.toLowerCase().includes(q) || s.name.toLowerCase().includes(q) || s.sector.toLowerCase().includes(q)',
  '    );',
  '    setSearchResults(filtered.slice(0, 6));',
  '  }, [searchQuery, quotes]);',
  '',
  '  return (',
  '    <header className="sticky top-0 z-20 w-full bg-bg-primary/85 backdrop-blur-md border-b border-border-subtle px-4 sm:px-6 py-3.5 flex items-center justify-between gap-3">',
  '      {/* Search bar with quick results dropdown */}',
  '      <div className="relative flex-1 max-w-xs sm:max-w-md">',
  '        <div className="relative flex items-center">',
  '          <Search className="absolute left-3.5 w-4 h-4 text-text-muted" />',
  '          <input',
  '            type="text"',
  '            value={searchQuery}',
  '            onChange={e => {',
  '              setSearchQuery(e.target.value);',
  '              setIsSearchOpen(true);',
  '            }}',
  '            onFocus={() => setIsSearchOpen(true)}',
  '            placeholder="Search Reliance, HDFC, IT..."',
  '            className="w-full bg-bg-secondary border border-border-subtle rounded-xl pl-9 pr-4 py-2 text-xs sm:text-sm text-text-primary placeholder:text-text-muted focus:outline-none focus:ring-1 focus:ring-brand-accent focus:border-brand-accent transition-colors"',
  '          />',
  '        </div>',
  '',
  '        {/* Dropdown search results */}',
  '        {isSearchOpen && searchResults.length > 0 && (',
  '          <>',
  '            <div',
  '              className="fixed inset-0 z-10"',
  '              onClick={() => setIsSearchOpen(false)}',
  '            />',
  '            <div className="absolute left-0 right-0 top-full mt-2 bg-bg-card border border-border-subtle rounded-2xl shadow-2xl overflow-hidden z-20 py-2">',
  '              {searchResults.map(stock => (',
  '                <div',
  '                  key={stock.symbol}',
  '                  onClick={() => {',
  '                    openStockModal(stock.symbol);',
  '                    setIsSearchOpen(false);',
  '                    setSearchQuery("");',
  '                  }}',
  '                  className="flex items-center justify-between px-4 py-2.5 hover:bg-bg-elevated cursor-pointer transition-colors"',
  '                >',
  '                  <div>',
  '                    <div className="flex items-center gap-2">',
  '                      <span className="text-xs font-bold text-text-primary">{stock.symbol}</span>',
  '                      <span className="text-[10px] text-text-muted px-1.5 py-0.5 rounded bg-bg-secondary border border-border-subtle/60">',
  '                        {stock.sector}',
  '                      </span>',
  '                    </div>',
  '                    <p className="text-[11px] text-text-secondary truncate max-w-[160px]">{stock.name}</p>',
  '                  </div>',
  '                  <div className="text-right">',
  '                    <div className="text-xs font-bold text-text-primary">₹{stock.price.toFixed(2)}</div>',
  '                    <div className={`text-[10px] font-semibold ${stock.change >= 0 ? "text-brand-positive" : "text-brand-negative"}`}>',
  '                      {stock.change >= 0 ? "+" : ""}{stock.changePercent}%',
  '                    </div>',
  '                  </div>',
  '                </div>',
  '              ))}',
  '            </div>',
  '          </>',
  '        )}',
  '      </div>',
  '',
  '      {/* Right controls: Market Status, Clock, Theme, CTAs */}',
  '      <div className="flex items-center gap-2 sm:gap-3.5">',
  '        {/* Market Status Badge */}',
  '        <div className="hidden lg:flex items-center gap-2 px-3 py-1.5 rounded-xl bg-bg-secondary border border-border-subtle text-xs">',
  '          <span className={`w-2 h-2 rounded-full ${marketStatus.isOpen ? "bg-brand-positive animate-pulse" : "bg-brand-negative"}`} />',
  '          <span className="font-semibold text-text-primary">{marketStatus.status}</span>',
  '          <span className="text-text-muted">({marketStatus.timeUntilNext})</span>',
  '        </div>',
  '',
  '        {/* IST Clock */}',
  '        <div className="hidden sm:flex items-center gap-1.5 text-xs text-text-secondary px-2.5 py-1.5 rounded-xl bg-bg-secondary border border-border-subtle font-mono">',
  '          <Clock className="w-3.5 h-3.5 text-brand-accent" />',
  '          <span>{istTime}</span>',
  '        </div>',
  '',
  '        {/* Theme Toggle */}',
  '        <button',
  '          onClick={toggleTheme}',
  '          className="p-2 rounded-xl bg-bg-secondary border border-border-subtle text-text-secondary hover:text-text-primary hover:bg-bg-elevated transition-colors"',
  '          aria-label="Toggle theme"',
  '        >',
  '          {theme === "dark" ? <Sun className="w-4 h-4 text-brand-accent" /> : <Moon className="w-4 h-4 text-slate-700" />}',
  '        </button>',
  '',
  '        {/* Log Trade CTA */}',
  '        <Button',
  '          variant="primary"',
  '          size="sm"',
  '          icon={<Plus className="w-3.5 h-3.5" />}',
  '          onClick={() => setIsNewTradeModalOpen(true)}',
  '          className="hidden sm:inline-flex"',
  '        >',
  '          Log Trade',
  '        </Button>',
  '      </div>',
  '    </header>',
  '  );',
  '};'
].join('\n'));

// 3. BottomNav.tsx
fs.writeFileSync(path.join(srcDir, 'components/layout/BottomNav.tsx'), [
  'import React from "react";',
  'import {',
  '  LayoutDashboard,',
  '  TrendingUp,',
  '  Calculator,',
  '  BookOpen,',
  '  Briefcase,',
  '  User',
  '} from "lucide-react";',
  'import { useApp } from "../../context/AppContext";',
  '',
  'export const BottomNav: React.FC = () => {',
  '  const { activeTab, setActiveTab } = useApp();',
  '',
  '  const navItems = [',
  '    { id: "dashboard", label: "Home", icon: <LayoutDashboard className="w-5 h-5" /> },',
  '    { id: "markets", label: "Markets", icon: <TrendingUp className="w-5 h-5" /> },',
  '    { id: "planner", label: "Trade", icon: <Calculator className="w-5 h-5" /> },',
  '    { id: "journal", label: "Journal", icon: <BookOpen className="w-5 h-5" /> },',
  '    { id: "paper", label: "Paper", icon: <Briefcase className="w-5 h-5" /> },',
  '    { id: "settings", label: "Profile", icon: <User className="w-5 h-5" /> }',
  '  ];',
  '',
  '  return (',
  '    <nav className="md:hidden fixed bottom-0 left-0 right-0 z-40 bg-bg-secondary/95 backdrop-blur-lg border-t border-border-subtle px-2 py-1.5 flex items-center justify-around shadow-2xl safe-area-inset-bottom">',
  '      {navItems.map(item => {',
  '        const isActive = activeTab === item.id;',
  '        return (',
  '          <button',
  '            key={item.id}',
  '            onClick={() => setActiveTab(item.id)}',
  '            className={`flex flex-col items-center justify-center py-1 px-2.5 rounded-xl transition-all duration-150 ${',
  '              isActive ? "text-brand-accent font-semibold" : "text-text-muted hover:text-text-secondary"',
  '            }`}',
  '          >',
  '            <div className={`p-1 rounded-lg ${isActive ? "bg-brand-accent/15" : ""}`}>{item.icon}</div>',
  '            <span className="text-[10px] mt-0.5 tracking-tight">{item.label}</span>',
  '          </button>',
  '        );',
  '      })}',
  '    </nav>',
  '  );',
  '};'
].join('\n'));

// 4. AppLayout.tsx
fs.writeFileSync(path.join(srcDir, 'components/layout/AppLayout.tsx'), [
  'import React from "react";',
  'import { Sidebar } from "./Sidebar";',
  'import { Header } from "./Header";',
  'import { BottomNav } from "./BottomNav";',
  '',
  'interface AppLayoutProps {',
  '  children: React.ReactNode;',
  '}',
  '',
  'export const AppLayout: React.FC<AppLayoutProps> = ({ children }) => {',
  '  return (',
  '    <div className="min-h-screen bg-bg-primary flex">',
  '      {/* Desktop Sidebar Navigation */}',
  '      <Sidebar />',
  '',
  '      {/* Main Content Area */}',
  '      <div className="flex-1 flex flex-col min-w-0 pb-20 md:pb-8">',
  '        <Header />',
  '        <main className="flex-1 p-4 sm:p-6 lg:p-8 max-w-7xl w-full mx-auto animate-fadeIn">',
  '          {children}',
  '        </main>',
  '      </div>',
  '',
  '      {/* Mobile Bottom Navigation Bar */}',
  '      <BottomNav />',
  '    </div>',
  '  );',
  '};'
].join('\n'));

console.log('Layout components created successfully');
