const fs = require('fs');
const path = require('path');
const srcDir = path.resolve(__dirname, '..', 'src');

fs.writeFileSync(path.join(srcDir, 'context/MarketDataContext.tsx'), [
  'import React, { createContext, useContext, useEffect, useState, useCallback } from "react";',
  'import { MarketQuote, IndexData, TimeFrame, HistoricalPrice } from "../types";',
  'import { MarketDataService } from "../services/MarketDataService";',
  '',
  'interface MarketStatus {',
  '  isOpen: boolean;',
  '  status: string;',
  '  nextEvent: string;',
  '  timeUntilNext: string;',
  '}',
  '',
  'interface MarketDataContextType {',
  '  quotes: MarketQuote[];',
  '  indices: IndexData[];',
  '  marketStatus: MarketStatus;',
  '  isLoading: boolean;',
  '  getQuote: (symbol: string) => MarketQuote | undefined;',
  '  getHistoricalData: (symbol: string, timeframe: TimeFrame) => Promise<HistoricalPrice[]>;',
  '  searchStocks: (query: string) => Promise<MarketQuote[]>;',
  '  refreshData: () => Promise<void>;',
  '  selectedStockSymbol: string | null;',
  '  setSelectedStockSymbol: (symbol: string | null) => void;',
  '  openStockModal: (symbol: string) => void;',
  '  closeStockModal: () => void;',
  '}',
  '',
  'const MarketDataContext = createContext<MarketDataContextType | undefined>(undefined);',
  '',
  'export const MarketDataProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {',
  '  const [quotes, setQuotes] = useState<MarketQuote[]>([]);',
  '  const [indices, setIndices] = useState<IndexData[]>([]);',
  '  const [marketStatus, setMarketStatus] = useState<MarketStatus>({',
  '    isOpen: true,',
  '    status: "MARKET OPEN",',
  '    nextEvent: "Closes at 03:30 PM IST",',
  '    timeUntilNext: "Open"',
  '  });',
  '  const [isLoading, setIsLoading] = useState(true);',
  '  const [selectedStockSymbol, setSelectedStockSymbol] = useState<string | null>(null);',
  '',
  '  const loadData = useCallback(async () => {',
  '    try {',
  '      const [quotesData, indicesData] = await Promise.all([',
  '        MarketDataService.getAllQuotes(),',
  '        MarketDataService.getIndices()',
  '      ]);',
  '      setQuotes(quotesData);',
  '      setIndices(indicesData);',
  '      setMarketStatus(MarketDataService.isMarketOpen());',
  '    } catch (error) {',
  '      console.error("Failed to load market data:", error);',
  '    } finally {',
  '      setIsLoading(false);',
  '    }',
  '  }, []);',
  '',
  '  useEffect(() => {',
  '    loadData();',
  '',
  '    // Subtle simulated price updates every 3 seconds to emulate live market ticks',
  '    const interval = setInterval(() => {',
  '      setQuotes(prev =>',
  '        prev.map(stock => {',
  '          const delta = (Math.random() - 0.49) * (stock.price * 0.0008);',
  '          const newPrice = Math.max(1, Math.round((stock.price + delta) * 100) / 100);',
  '          const change = Math.round((newPrice - stock.prevClose) * 100) / 100;',
  '          const changePercent = Math.round((change / stock.prevClose) * 10000) / 100;',
  '          const newSparkline = [...stock.sparkline.slice(1), newPrice];',
  '',
  '          return {',
  '            ...stock;',
  '            price: newPrice,',
  '            change,',
  '            changePercent,',
  '            high: Math.max(stock.high, newPrice),',
  '            low: Math.min(stock.low, newPrice),',
  '            sparkline: newSparkline,',
  '            lastUpdated: new Date().toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit", second: "2-digit" })',
  '          };',
  '        })',
  '      );',
  '',
  '      setIndices(prev =>',
  '        prev.map(idx => {',
  '          const delta = (Math.random() - 0.49) * (idx.price * 0.0004);',
  '          const newPrice = Math.max(1, Math.round((idx.price + delta) * 100) / 100);',
  '          const change = Math.round((idx.change + delta) * 100) / 100;',
  '          const changePercent = Math.round((change / (idx.price - idx.change)) * 10000) / 100;',
  '          const newSparkline = [...idx.sparkline.slice(1), newPrice];',
  '          return {',
  '            ...idx;',
  '            price: newPrice,',
  '            change,',
  '            changePercent,',
  '            isPositive: change >= 0,',
  '            sparkline: newSparkline',
  '          };',
  '        })',
  '      );',
  '',
  '      setMarketStatus(MarketDataService.isMarketOpen());',
  '    }, 3000);',
  '',
  '    return () => clearInterval(interval);',
  '  }, [loadData]);',
  '',
  '  const getQuote = (symbol: string) => {',
  '    return quotes.find(q => q.symbol.toUpperCase() === symbol.toUpperCase());',
  '  };',
  '',
  '  const getHistoricalData = (symbol: string, timeframe: TimeFrame) => {',
  '    return MarketDataService.getHistoricalData(symbol, timeframe);',
  '  };',
  '',
  '  const searchStocks = (query: string) => {',
  '    return MarketDataService.searchStocks(query);',
  '  };',
  '',
  '  const openStockModal = (symbol: string) => {',
  '    setSelectedStockSymbol(symbol);',
  '  };',
  '',
  '  const closeStockModal = () => {',
  '    setSelectedStockSymbol(null);',
  '  };',
  '',
  '  return (',
  '    <MarketDataContext.Provider',
  '      value={{',
  '        quotes,',
  '        indices,',
  '        marketStatus,',
  '        isLoading,',
  '        getQuote,',
  '        getHistoricalData,',
  '        searchStocks,',
  '        refreshData: loadData,',
  '        selectedStockSymbol,',
  '        setSelectedStockSymbol,',
  '        openStockModal,',
  '        closeStockModal',
  '      }}',
  '    >',
  '      {children}',
  '    </MarketDataContext.Provider>',
  '  );',
  '};',
  '',
  'export const useMarketData = () => {',
  '  const context = useContext(MarketDataContext);',
  '  if (!context) throw new Error("useMarketData must be used within MarketDataProvider");',
  '  return context;',
  '};'
].map(line => line.replace('...stock;', '...stock,').replace('...idx;', '...idx,')).join('\n'));

console.log('MarketDataContext.tsx written');
