const fs = require('fs');
const path = require('path');
const srcDir = path.resolve(__dirname, '..', 'src');

fs.writeFileSync(path.join(srcDir, 'context/ThemeContext.tsx'), [
  'import React, { createContext, useContext, useEffect, useState } from "react";',
  '',
  'type Theme = "dark" | "light";',
  '',
  'interface ThemeContextType {',
  '  theme: Theme;',
  '  toggleTheme: () => void;',
  '  setTheme: (theme: Theme) => void;',
  '}',
  '',
  'const ThemeContext = createContext<ThemeContextType | undefined>(undefined);',
  '',
  'export const ThemeProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {',
  '  const [theme, setThemeState] = useState<Theme>(() => {',
  '    if (typeof window !== "undefined") {',
  '      const saved = localStorage.getItem("tw_theme");',
  '      if (saved === "dark" || saved === "light") return saved;',
  '    }',
  '    return "dark";',
  '  });',
  '',
  '  useEffect(() => {',
  '    const root = document.documentElement;',
  '    if (theme === "dark") {',
  '      root.classList.add("dark");',
  '      root.classList.remove("light");',
  '    } else {',
  '      root.classList.add("light");',
  '      root.classList.remove("dark");',
  '    }',
  '    localStorage.setItem("tw_theme", theme);',
  '  }, [theme]);',
  '',
  '  const toggleTheme = () => {',
  '    setThemeState(prev => (prev === "dark" ? "light" : "dark"));',
  '  };',
  '',
  '  const setTheme = (newTheme: Theme) => {',
  '    setThemeState(newTheme);',
  '  };',
  '',
  '  return (',
  '    <ThemeContext.Provider value={{ theme, toggleTheme, setTheme }}>',
  '      {children}',
  '    </ThemeContext.Provider>',
  '  );',
  '};',
  '',
  'export const useTheme = () => {',
  '  const context = useContext(ThemeContext);',
  '  if (!context) throw new Error("useTheme must be used within ThemeProvider");',
  '  return context;',
  '};'
].join('\n'));

console.log('ThemeContext.tsx written');
